### ISSUE TITLE
error on: npm run bootstrap

### ISSUE THREAD

**Issue by mnts** [ceramicstudio/self.id#1]
> self.id@0.1.0 bootstrap /home/mk/w/self.id
> node scripts/bootstrap

Error: Validation Error: data.image should be object, data.background should be object
    at Object.fetchJson (/home/mk/w/self.id/node_modules/@ceramicnetwork/http-client/lib/utils.js:18:15)

**Comment by PaulLeCam** [comment]
Outdated with current setup.
