### ISSUE TITLE
Stale "successful edit" notification

### ISSUE THREAD

**Issue by ukstv** [ceramicstudio/self.id#10]
Steps to reproduce:
1. Connect
2. Open edit profile dialog, change fields
3. Submit the edits
4. Open edit profile dialog
5. HERE: Green splash for "Profile successfully saved!"
It should be gone by now.

<img width="660" alt="Screenshot 2021-05-19 at 10 24 13" src="https://user-images.githubusercontent.com/193527/118772441-6c7d1100-b88c-11eb-8748-8c3e695e053f.png">

**Comment by PaulLeCam** [comment]
I replaced these with toast messages, should be fixed now.
