### ISSUE TITLE
"Saving profile..." indicator is of red hue

### ISSUE THREAD

**Issue by ukstv** [ceramicstudio/self.id#11]
Usually red is for errors.

<img width="734" alt="Screenshot 2021-05-19 at 10 24 01" src="https://user-images.githubusercontent.com/193527/118772647-a8b07180-b88c-11eb-84d9-a82b0da10453.png">

**Comment by PaulLeCam** [comment]
Should be replaced by a toast notification now

**Comment by ukstv** [comment]
Yup. For future reference:

<img width="310" alt="Screenshot 2021-05-19 at 19 50 29" src="https://user-images.githubusercontent.com/193527/118852457-7b3ee480-b8db-11eb-814d-00d71ec064ce.png">
