### ISSUE TITLE
Wrapping in name element does not support longer names

### ISSUE THREAD

**Issue by ukstv** [ceramicstudio/self.id#12]
Also, longer names squeeze the round avatar placeholder.

<img width="315" alt="Screenshot 2021-05-18 at 16 07 37" src="https://user-images.githubusercontent.com/193527/118772972-02b13700-b88d-11eb-97e5-940a330996d5.png">

<img width="336" alt="Screenshot 2021-05-18 at 16 09 06" src="https://user-images.githubusercontent.com/193527/118773029-0e9cf900-b88d-11eb-85d3-05cf3145d5d3.png">

<img width="316" alt="Screenshot 2021-05-18 at 16 11 39" src="https://user-images.githubusercontent.com/193527/118773146-32603f00-b88d-11eb-9237-68eed38535e1.png">

Continue on this theme: long German word `Donaudampfschiffahrtsgesellschaftskapitän`:

<img width="340" alt="Screenshot 2021-05-18 at 16 09 47" src="https://user-images.githubusercontent.com/193527/118773116-296f6d80-b88d-11eb-83c0-3fd38a9fb328.png">

**Comment by PaulLeCam** [comment]
Good catch, thanks! should be fixed in latest deployment

**Comment by ukstv** [comment]
Nice!

<img width="1036" alt="Screenshot 2021-05-19 at 19 47 41" src="https://user-images.githubusercontent.com/193527/118852084-1c796b00-b8db-11eb-87f4-7d017624aced.png">

**Comment by ukstv** [comment]
With the long German word and the dropdown open:

![Screenshot 2021-05-19 at 19 53 25](https://user-images.githubusercontent.com/193527/118852921-e688b680-b8db-11eb-85e9-7ea36aef1f6f.png)
