### ISSUE TITLE
Red hue for pretty normal text

### ISSUE THREAD

**Issue by ukstv** [ceramicstudio/self.id#13]
Usually, red is for errors.

<img width="600" alt="Screenshot 2021-05-18 at 16 13 35" src="https://user-images.githubusercontent.com/193527/118773357-6dfb0900-b88d-11eb-9080-404398081731.png">

**Comment by PaulLeCam** [comment]
It should use the pink one everywhere now

**Comment by ukstv** [comment]
Pink is much better. It still is red hue (~error) though, yet in the brand design. Let it sit. For my taste the text should be just black (+ opacity to 75%), but this would go off brand.

Pink be it till one has better idea what to do with this.
