### ISSUE TITLE
Edits are not immediately effective

### ISSUE THREAD

**Issue by ukstv** [ceramicstudio/self.id#14]
After you edit a profile, the content changes immediately. If you reload a page, it still displays old content. Checked on editing names and updating a banner.

Changed name, refreshed the page:
<img width="600" alt="Screenshot 2021-05-18 at 16 14 33" src="https://user-images.githubusercontent.com/193527/118773761-c9c59200-b88d-11eb-82ff-6af0d3886acf.png">

Changed name again, refreshed the page:
<img width="600" alt="Screenshot 2021-05-18 at 16 21 50" src="https://user-images.githubusercontent.com/193527/118773831-da760800-b88d-11eb-8f75-61aedb5fe960.png">

**Comment by ukstv** [comment]
Quite the same goes with a banner.
Steps:
1. Open "Edit profile",
2. Attach a banner image,
3. Submit the edits. This would show the banner just all right.
4. Refresh the page.
5. HERE: No banner present. All grey.
6. Open "Edit profile" dialog again.
7. HERE: Banner is here.

Below is a screenshot on step 7. No banner on the background, but it is present in the dialog.

<img width="600" alt="Screenshot 2021-05-18 at 16 58 58" src="https://user-images.githubusercontent.com/193527/118775428-98e65c80-b88f-11eb-9241-7e8f15b3e188.png">

**Comment by ukstv** [comment]
Continuing on this.
1. Edit profile with no banner attached: it is here.
2. Attach a new banner image.
3. HERE: Expectation: banner is changed. Reality: Nope.

<img width="1382" alt="Screenshot 2021-05-19 at 11 03 19" src="https://user-images.githubusercontent.com/193527/118777543-d77d1680-b891-11eb-8be2-14d3f5821c9c.png">

**Comment by ukstv** [comment]
I do not know what is the source of the discrepancy for sure. I understand content on the "Edit profile" dialog is fetched in browser, while the profile pane is populated on server side. Effectively both sides do a single `idx.get` call. My educated guess is caching is involved. Apparently, IDX uses [dataloader](https://github.com/graphql/dataloader) library for request batching and caching. And, it seems, it caches everything forever. So, it seems the profile pane content is only refreshed after a restart of server-side Vercel instance. My best guess is to not use dataloader: https://github.com/ceramicstudio/js-idx/pull/50 [would involve bumping IDX version].

**Comment by ukstv** [comment]
After IDX is released, we'll be able to use the change here.

**Comment by PaulLeCam** [comment]
Should be fixed with IDX update but please let me know if you see it again, there might be other issues with local storage caching maybe

**Comment by ukstv** [comment]
Works like magic for name and banner. Closing. Thanks @PaulLeCam!
