### ISSUE TITLE
Connect dialog on edit after refresh

### ISSUE THREAD

**Issue by ukstv** [ceramicstudio/self.id#15]
Steps:
1. Open profile,
2. Edit profile and populate it with something,
3. Refresh the window
4. Click on "Edit" button
5. HERE: It asks me to sign in.

By itself, the behaviour is all right: private keys, entropy and such, but the app already knows my ID and my profile, so this is a bit confusing. Maybe add some explanation on top of the network/wallet selector?

<img width="600" alt="Screenshot 2021-05-18 at 16 20 01" src="https://user-images.githubusercontent.com/193527/118775038-2c6b5d80-b88f-11eb-8480-1036a6519708.png">

**Comment by PaulLeCam** [comment]
Updating the modal would be more involved as it's driven by multiauth, but I replaced the button label by "Connect to edit" so hopefully it's more explicit the modal will appear.

**Comment by ukstv** [comment]
Yay! This is cool.

**Comment by ukstv** [comment]
Added an issue to multiauth to mitigate that in the next iterations https://github.com/ceramicstudio/multiauth/issues/1
