### ISSUE TITLE
Name is lost

### ISSUE THREAD

**Issue by ukstv** [ceramicstudio/self.id#16]
While in #14 I whined about changes being not effective on the profile pane, now (2021-05-19) it goes into full discordance.

Profile is https://self.id/did:3:kjzl6cwe1jw14bgy1miryygnrf7mbl2598t1e8ziyk29cgfgigr6utkblokom5r

Actions before screenshot:
1. Open profile with present name "Just a Hobbit"
2. Changed the name to "Just a Hobbit For Gods Sake"
3. Refreshed the window.
4. Screenshot: Opened "Edit profile"

3id name banner: displays just DID "did:3:kjzl..."
Profile pane: "Just a Hobbit"
Edit dialog: "Just a Hobbit For Gods Sake"

<img width="1189" alt="Screenshot 2021-05-19 at 10 53 06" src="https://user-images.githubusercontent.com/193527/118776217-6b4de300-b890-11eb-9d0f-2b0de620d71c.png">

Just to be clear, I moved the dialog to the right via Chrome Dev Console to display all three names.

**Comment by PaulLeCam** [comment]
Probably related to IDX caching but please let me know if you see it using the latest version

**Comment by ukstv** [comment]
Yup. Seems to work! Closing.
