### ISSUE TITLE
When clicking "Connect" button on the welcome page for the first time, the whole page flickers

### ISSUE THREAD

**Issue by ukstv** [ceramicstudio/self.id#19]
I guess it has something to do with how React components are organised.

https://user-images.githubusercontent.com/193527/118779031-545cc000-b893-11eb-94c2-1848a00f87a0.mov

**Comment by PaulLeCam** [comment]
@ukstv are you seeing this consistently please? I haven't been able to reproduce it.

**Comment by ukstv** [comment]
Yes. I just have to refresh the page first.

Opened a fresh page and saw this: https://1drv.ms/v/s!AlrUNK8nVibvg-tcL5VoByWdqYC81A?e=q2p53h

**Comment by ukstv** [comment]
I suspect it might be because of Grommet trying to replace CSS styling with manual React rendering, but do not really know.
