### ISSUE TITLE
Indicate 3id-connect progress

### ISSUE THREAD

**Issue by ukstv** [ceramicstudio/self.id#21]
Currently it is the same default avatar. Better be a spinner.

<img width="287" alt="Screenshot 2021-05-19 at 11 17 55" src="https://user-images.githubusercontent.com/193527/118779653-ed8bd680-b893-11eb-9546-6e4edfda3884.png">

**Comment by PaulLeCam** [comment]
Yes good idea, I replaced it

**Comment by ukstv** [comment]
Works and looks fabulous. Closing.
