### ISSUE TITLE
"No profile found" on profile pane is rude and non-actionable

### ISSUE THREAD

**Issue by ukstv** [ceramicstudio/self.id#24]
Should be “The profile is empty, please edit it” or something like it.

**Comment by ukstv** [comment]
@michaelsena What is the good wording here?

**Comment by PaulLeCam** [comment]
This is essentially a "404 Not found" when trying to load a profile that doesn't exist, so obviously we can change the message but that can apply to any profile, not necessarily one the user could edit.
We should discuss further the possible cases here, between the profile being loaded or not, valid or not (not a valid or supported DID method for example), and editable by the user (which we can't know for sure until they authenticate).

**Comment by ukstv** [comment]
Wow, this is deep.

**Comment by ukstv** [comment]
@PaulLeCam How do you feel about just "No profile", or "No profile yet"?

**Comment by PaulLeCam** [comment]
Yeah it can be what we want, eventually we'll want a real onboarding flow but that wasn't a priority.
I don't mind changing to "No profile" or "No profile yet" if you want but as I commented above, there are many cases that can lead to displaying this, including invalid/unsupported DIDs so I think it's a behavior we should really specify.

**Comment by ukstv** [comment]
Changed to "No Profile" in https://github.com/ceramicstudio/self.id/pull/26

**Comment by ukstv** [comment]
Consider fixed. Closing for now.
