### ISSUE TITLE
invaliDid

### ISSUE THREAD

**Issue by Sactorum** [ceramicstudio/self.id#28]
![image](https://user-images.githubusercontent.com/45465932/120473843-bf37ec00-c3a7-11eb-9c3d-7eea362a4dae.png)
I have tried to connect one of my MetaMask accounts to a local running self.id server, but this ocurred.
then I tried using another MetaMask accoun to connecto to an existing DID, which I selected the one that os shown in the imagen, but the same error ocurred.
What's going on? I'm I missing somenithg to load onto the ceramic daemoin?

**Comment by PaulLeCam** [comment]
If you use the app in a local setup, you need to also run local Ceramic and 3ID Connect servers, which might be a bit tricky as the whole setup is still being worked on.
Do you have a specific reason for trying to run this app locally please? This is mostly an internal project for us, not an app we expect other people to work on or deploy, at least at this stage.
