### ISSUE TITLE
Show warning when not connected to mainnet

### ISSUE THREAD

**Issue by scottrepreneur** [ceramicstudio/self.id#33]
It's unclear when you're not connected to mainnet and attempting to link other network dids to your mainnet one instead of just wanting the already existing one. Indicate that the user is not on mainnet when connected so they only attempt to create DID profiles on mainnet for now. Probably related to #9 .

Steps to reproduce
1. create did and migrate 3box to idx from mainnet
2. reconnect wallet with network switched
3. attempt to sign into did and return different one
4. 3ID connect asks to migrate 3box profile but fails

**Comment by oed** [comment]
This seems like it could be an issue with 3ID Connect. The same wallet on different networks can in theory have different identities. That's why this error is appearing most likely.
