### ISSUE TITLE
Profile updates are not being persisted

### ISSUE THREAD

**Issue by oed** [ceramicstudio/self.id#37]
When saving an update to a profile it is not being persisted. Use the following steps to reproduce:

1. Make sure you have a profile on 3box.io
2. Log in to clay.self.id
3. Update your profile picture and press save
4. Log out of clay.self.id
5. Log in to clay.self.id again
6. You will now have your profile reverted to your first profile picture 

I've also observed this on self.id. Not sure if this is an issue in self.id or 3id-connect, but on my profile I only see one commit in the basicProfile: https://gateway-clay.ceramic.network/api/v0/streams/kjzl6cwe1jw145cjbeko9kil8g9bxszjhyde21ob8epxuxkaon1izyqsu8wgcic

**Comment by PaulLeCam** [comment]
I just went through the flow as described but I couldn't reproduce the issue, my profile is correctly updated.
Could it have been a temporary issue due to a bug in 3ID Connect or a problem with the infra?

**Comment by zachferland** [comment]
Yeah i believe this overlapped with the infra issue, going to close for now
