### ISSUE TITLE
get internal DID instance for JOSE JWE JWS 

### ISSUE THREAD

**Issue by franleplant** [ceramicstudio/self.id#47]
# Description

I am trying to follow this tutorial https://blog.ceramic.network/how-to-store-signed-and-encrypted-data-on-ipfs/ to
store JWE and JWS data into IPFS and I need to get the DID instance but my app is authenticated through self.ID and it looks like
the DID instance is private. 

How can I combine both techniques? 

# Technical Information

Maybe just explain / document what would be the "right" way of using these two techniques together or expose the DID instance  out of the self.id instance.

**Comment by PaulLeCam** [comment]
The `SelfID` class exposes the internal `did`, which should cover this use-case: https://developers.ceramic.network/reference/self-id/classes/web.SelfID/#did
