### ISSUE TITLE
Unable to connect with a smart contract wallet

### ISSUE THREAD

**Issue by michael60634** [ceramicstudio/self.id#48]
# Description

Unable to connect via WalletConnect using a smart contract wallet.

# Technical Information

https://docs.argent.xyz/wallet-connect-and-argent

**Comment by PaulLeCam** [comment]
This is not something we currently support or have plan to at the moment.

**Comment by michael60634** [comment]
So there will be no support at any time in the future? If so, that's incredibly disappointing.

**Comment by oed** [comment]
@michael60634 We will support all contract wallets that support eip1271 and Sign-in with Ethereum in the future.

**Comment by PaulLeCam** [comment]
The Self.ID app is mainly a reference/demo app for the Self.ID SDK showcasing how the Ceramic stack can be used, it's not meant to grow beyond this scope.
That doesn't mean libraries and apps couldn't use contract wallets when using Ceramic or that we wouldn't provide more tools to support this in the future, simply that it's not something we're currently focusing on for Self.ID.
