### ISSUE TITLE
Login silently fails on an unrecognized chain id

### ISSUE THREAD

**Issue by dysbulic** [ceramicstudio/self.id#5]
When attempting to log in, if the chain is not in a specific set the login fails with no notification of why.

Since you're just signing stuff, do you need to care about the chain at all?

**Comment by oed** [comment]
Can you elaborate? Where is the chain not set?

**Comment by dysbulic** [comment]
> Where is the chain not set?

In MetaMask, I was on the xDAI chain.

In looking at the format of CAIP-10, it includes the chain id, so maybe you do have to limit it to a specific set, but it would still be nice to get an on-screen notification that the chain needs to be changed.

**Comment by zachferland** [comment]
I tried to replicate this issue, and got the following:

1) no problem in 3id-connect/authprovider creating a did using an xDAI account 
2) in self.id got a warning 
```
 Failed to login: e: Unsupported chain id: 100. Supported chain ids are: 1,3,4,5,42.
```
but yeah no visual feedback yet 

I guess the fix here is to just allow any chain id (as long as provider supported), and/or given some basic visual feedback to user in self.id 

cc @PaulLeCam

**Comment by PaulLeCam** [comment]
Thanks for looking into this!
Sorry I forgot about this configuration for the injected provider in self.id, this chain ID restriction should be removed now.
