### ISSUE TITLE
Loader error on @self.id/framework

### ISSUE THREAD

**Issue by tmoutinho** [ceramicstudio/self.id#51]
# Description

Hey guys, trying to implement the Profile id in our site but keep getting this error,

```
./node_modules/@self.id/framework/dist/lib.mjs 100:15
Module parse failed: Unexpected token (100:15)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|     ...i
|   } = e,
>         o = t ?? {},
|         c = r ?? {};
|   return a.createElement(g, { ...c
```

# Technical Information

We use typescript and a simple create react app, with react-app-rewired.
I have copied the webpack-basic-typescript example, but this error is strange one.

Thanks in advance for any help.

**Comment by PaulLeCam** [comment]
Hi, what version of Create React App are you using please? If it's v4 it's not supported, please upgrade to v5.

**Comment by tmoutinho** [comment]
Hi Paul, I have `"react-scripts": "^3.0.0"`. I will upgrade it and test it again. Thanks.
