### ISSUE TITLE
Profile image is not being updated

### ISSUE THREAD

**Issue by exrhizo** [ceramicstudio/self.id#52]
on self.id

I upload an image,
and according to network it seems to work:
https://cloudflare-ipfs.com/ipfs/QmUvG66PoAs9tyMAAMMxgBn66JMbtT9JXM5XVgJnsxsD3H
(the UI doesn't show this change, although it shows my custom background)

But it doesn't show up in my app that is using,
`import { BasicProfile } from '@datamodels/identity-profile-basic';`

Although the other data does show up, not sure how to debug

**Comment by PaulLeCam** [comment]
It could a temporary error on the network, are you still seeing the issue please?

**Comment by 0xGabi** [comment]
This is still an issue. I can't update my profile image using the site. The following warning is thrown:
<img width="1214" alt="Screen Shot 2022-03-04 at 1 39 20 PM" src="https://user-images.githubusercontent.com/9082013/156803356-07bf25eb-5f70-4c09-b745-1004dde9a5ca.png">

**Comment by PaulLeCam** [comment]
From the error message it seems to be an issue with your browser configuration.
