### ISSUE TITLE
import error of CommonJS modules 

### ISSUE THREAD

**Issue by greatpie** [ceramicstudio/self.id#53]
when I run ``npm dev``:

```
SyntaxError: Named export 'EthereumAuthProvider' not found. The requested module '@3id/connect' is a CommonJS module, which may not support all module.exports as named exports.
```

**Comment by jonathantcrawford** [comment]
Any idea when these templates will be working again?

**Comment by oed** [comment]
@PaulLeCam Will this be fixed with the next release of the selfId sdk?

**Comment by PaulLeCam** [comment]
That seems like a setup issue, @jonathantcrawford what template is not working for you please?

**Comment by vindecodex** [comment]
> when I run `npm dev`:
> 
> ```
> SyntaxError: Named export 'EthereumAuthProvider' not found. The requested module '@3id/connect' is a CommonJS module, which may not support all module.exports as named exports.
> ```

Same issue a run into, this was on nextjs template. @PaulLeCam

**Comment by vindecodex** [comment]
i just make it worked by using require instead of direct usage of import.

error
```js
import { EthereumAuthProvider, SelfID } from '@self.id/web';
```

no error
```js
const _web = require('@self.id/web');
const { EthereumAuthProvider, SelfID } = _web;
```

**Comment by kitakaze-kan** [comment]
Hi, I had same issue on Nextjs template.
It seems to be the same issue as https://github.com/vercel/next.js/issues/30750 .

Downgrading Next@12.0.1 works for me.

Or,  this method may work as well. (I haven't tried it.)
> For note, with v12.0.4 & react-hook-form, it's only ok with esmExternals: false

**Comment by jonathantcrawford** [comment]
> i just make it worked by using require instead of direct usage of import.
> 
> error
> 
> ```js
> import { EthereumAuthProvider, SelfID } from '@self.id/web';
> ```
> 
> no error
> 
> ```js
> const _web = require('@self.id/web');
> const { EthereumAuthProvider, SelfID } = _web;
> ```
> 
> I'm using NextJS
 @vindecodex where did you make this change in the nextjs template?

**Comment by jonathantcrawford** [comment]
Setting the next dependency to an explicit version worked for me.
```"next": "12.0.1",```

**Comment by kinshukk** [comment]
Still getting this error, but setting next dependency works for now, as @jonathantcrawford pointed out

**Comment by bananaspliff** [comment]
i have the same error with next template on windows10 / node16 / npm7

**Comment by bananaspliff** [comment]
if you can't publish notes after upgraded to 12.0.1 you need to enable chrome://flags/#unsafely-treat-insecure-origin-as-secure

**Comment by vindecodex** [comment]
> > i just make it worked by using require instead of direct usage of import.
> > error
> > ```js
> > import { EthereumAuthProvider, SelfID } from '@self.id/web';
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > no error
> > ```js
> > const _web = require('@self.id/web');
> > const { EthereumAuthProvider, SelfID } = _web;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I'm using NextJS
> 
> @vindecodex where did you make this change in the nextjs template?

i used nextjs `npx create-next-app` and not use the `@self.id/framework` instead i use `@self.id/web` and `@self.id/core`

**Comment by PaulLeCam** [comment]
I pushed new versions of the packages that remove the ESM setup, it works as expected for the self.id app and templates so hopefully this will fix the issues you're seeing.
