### ISSUE TITLE
Trying to "connect to an existing account" with no existing account hangs forever

### ISSUE THREAD

**Issue by stbrody** [ceramicstudio/self.id#8]
To repro:
* Go to self.id
* Click "connect"
* Select Metamask
* Click "continue" when asked about the site accessing your personal data
* When given the option to Connect to Existing ID or Create a new ID, click Connect to Existing ID
* Nothing happens
* wait
* still nothing happens
* Now try to click "Create a new ID"
* A spinning circle loading icon appears next to the "create a new ID" text
* wait
* nothing ever happens

Notice how not only does clicking "connect to an existing account" seem to hang without doing anything, it also then makes it so the "create a new ID" button then will also hang.

**Comment by rogargon** [comment]
Experiencing a similar issue. Took a look at the console and saw the following error, which seems a CORS error:

Access to XMLHttpRequest at 'https://ceramic-private-dev.3boxlabs.com/api/v0/multiqueries' from origin 'https://self-id.vercel.app' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by zachferland** [comment]
First part will be resolved on next release (including 0.1.4 3id-connect), the second part is due to requests only being allowed by self.id and subdomains, cors error expected from selfid.vercel.app at moment.

**Comment by ukstv** [comment]
@stbrody It works for me now on self.id

**Comment by rogargon** [comment]
Yes, working for me too from self.id 
It might be worth redirecting the old URL to this one

**Comment by stbrody** [comment]
Yeah, I no longer get the prompt at all that asks me to either "Connect to Existing ID" or "Create a new ID".  Now it just goes directly into the create a new ID flow.

Closing this issue as it seems resolved
