### ISSUE TITLE
@self.id/web has issues installing in v0.4.3

### ISSUE THREAD

**Issue by ShravanSunder** [ceramicstudio/self.id#84]
# Description

Provide a 2-3 sentence overview of the work to be done.
The installation with yarn fails in v0.4.3.  Works fine in earlier. versions 0.4.2.

<img width="622" alt="2022 09 21-22 36-Code package json — 2022-09-dpatron-experiments" src="https://user-images.githubusercontent.com/5294949/191645910-ed01e865-4ba9-475b-9676-0b86af7dfa2c.png">

# Technical Information

Looks like there was a wrong import in the package for the dids depedancy.

**Comment by ShravanSunder** [comment]
Same issue in all 0.3.x @self.id/framework

**Comment by zachferland** [comment]
dids package was fixed, if you remove all dependencies (and maybe locks) and install again you should be ok

thanks for creating an issue

**Comment by zachferland** [comment]
closing issue, please reopen if it continues, thanks!
