### ISSUE TITLE
Switching Eth networks still brings you to same profile

### ISSUE THREAD

**Issue by stbrody** [ceramicstudio/self.id#9]
To repro:
* Set metamask to be on Ropsten network
* go to self.id, create a new profile
* Update profile to set name
* log out
* go back to main self.id page
* click "connect"
* No prompt about whether you want to create a new ID or link to an existing
* Get a prompt from metamask to sign a message to "Allow this account to control your identity"
* Now you're brought to the same profile that was created before, as expected
* Now log out again
* Switch metamask to eth mainnet
* Go back to root self.id page
* Click connect
* Get prompt to create a new ID or link to existing, select create a new ID
* Sign message to "Allow this account to control your identity"
* Sign message to "Link this account to your identity"
* Get brought to the same account that was created on ropsten

Note that if you log out and log back in, the behavior through the login process is different depending on if you are on mainnet or ropsten.  If you log in via the same eth network that the account was originally created on, there's no prompt about creating a new ID vs linking to an existing one, and there is also no need to sign the "link this account to your identity" message in metamask.  But when connecting on a different eth network you get both those steps in the login flow, but then wind up at the same profile.

Note the extra steps to select new vs existing ID and to sign the extra message from metamask both seem to only happen the first time you log in with a new network. The subsequent login attempts behave the same as if you try to log in on the original network.

An example account I logged went through this process with: https://self.id/did:3:kjzl6cwe1jw14a27slbhxmfdinmaf55l9zeierq4lp4um4lbp3fzyossxndon6o

**Comment by ukstv** [comment]
Same experience. Do not know if it is a bug or a feature.

**Comment by ukstv** [comment]
@PaulLeCam @michaelsena @zachferland Mind elaborating on the expectation here? Is it a bug or a feature?
